---
- name: Restart the OpenSSH server - Debian
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart the OpenSSH server - RedHat
  ansible.builtin.service:
    name: sshd
    state: restarted
